# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/virtualisation/proxmox-lxc.nix") ];
  # imports = [ (modulesPath + "/virtualisation/qemu-vm.nix") ]; #TODO uncomment this line if you want to generate a QEMU vm

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
