name: "Generate LXC containers"
on:
  push:
    tags:
     - "**"

jobs:
  generate_jellyfin_lxc_container:
    name: Generate Jellyfin LXC container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      # - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Generate Jellyfin LXC container
        run: |
          nix build .#nixosConfigurations.jellyfin.config.formats.proxmox-lxc
          mv result jellyfin.tar.xz
      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          path: jellyfin.tar.xz
          name: jellyfin.tar.xz
  release:
    name: Create Github release
    needs:
      [
        generate_jellyfin_lxc_container
      ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download archive
        uses: actions/download-artifact@v3
        with:
          path: ./assets/
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete ${{ github.ref_name }} --yes || true
          find ./assets -type f -print| xargs gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --generate-notes
